swagger: '2.0'
info:
  title: QuickBlox REST API, Session API.
  description: A set of REST API requests to work with QuickBlox session.
  version: 1.0
# the domain of the service
host: quickblox.com
# array of all schemes that QuickBlox API supports
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  /session.json:
    post:
      summary: Create session
      operationId: Create_Session_Id
      description: |
        Create session and retrieve session token. There are 6 sets of parameters you can pass:
          * minimal set of parameters (to create App session token)
          * minimal set of parameters plus **user[login]**/**user[email]** and **user[password]** (to create User session token)
          * minimal set of parameters plus **provider=facebook**, **keys[token]** (to create User session token based on Facebook user)
          * minimal set of parameters plus **provider=twitter**, **keys[token]** and **keys[secret]** (to create User session token based on Twitter user)
          * minimal set of parameters plus **provider=twitter_digits**, **twitter_digits[X-Auth-Service-Provider]** and **twitter_digits
          [X-Verify-Credentials-Authorization]** (to create User session token based on Twitter Digits user (SMS))
          * minimal set of parameters plus **provider=firebase_phone**, **firebase_phone[project_id]** and **firebase_phone[access_token]** (to create User session token based on Firebase phone user (SMS))
      parameters:
        - name: application_id
          in: formData
          description: The autogenerated unique identifier of your app. You can get this value from the [admin console](https://admin.quickblox.com/apps) of your QuickBlox account
          required: true
          type: integer
          default: 92
        - name: auth_key
          in: formData
          description: The authentication key associated with the app. You can get this value from the [admin console](https://admin.quickblox.com/apps) of your QuickBlox account
          required: true
          type: string
          default: WzRAY9vrGmb6FfP
        - name: timestamp
          in: formData
          description: The current UTC time formatted as a [Unix Timestamp](http://en.wikipedia.org/wiki/Unix_time). Needs to be accurate to within 60 minutes of NTP time. We suggest you synchronize time on your devices with NTP service.
          required: true
          type: integer
          default: 1473075233
        - name: nonce
          in: formData
          description: A number used to identify the request, the combination of timestamp and nonce must be unique. See [Cryptographic nonce](http://en.wikipedia.org/wiki/Cryptographic_nonce) on Wikipedia
          required: true
          type: integer
          default: 189463
        - name: signature
          in: formData
          description: This is a SHA-1 hash of the request generated using the app's authorization secret. The authorization secret can be found in the [admin console](https://admin.quickblox.com/apps) of your QuickBlox account. Follow [How to generate Signature](#Signature_generation) section.
          required: true
          type: string
          default: |
            eb0ec2d8c8184a3e62b4
            1da2afb6e8d690577fa4
        - name: user[login]
          in: formData
          description: The user's login to create User session with. You can pass **user[login]** or **user[email]** only.
          required: false
          type: string
          default: bukster
        - name: user[email]
          in: formData
          description: The user's email address to create User session with. You can pass **user[login]** or **user[email]** only.
          required: false
          type: string
          default: samuel@quickblox.com
        - name: user[password]
          in: formData
          description: The user's password to create User session with.
          required: false
          type: string
          default: bad-as-passwd
        - name: provider
          in: formData
          description: Name of the social network provider to create User session with, eg. **facebook**, **twitter**, **twitter_digits**, **firebase_phone**.
          required: false
          type: string
          default: facebook
        - name: keys[token]
          in: formData
          description: Your app's access token for the social network platform to create User session with.
          required: false
          type: string
          default: |
            AM46dxjhisdffgry262
            82352fdusdfusdfgsdf
        - name: keys[secret]
          in: formData
          description: Your app's access token secret for the social network platform to create User session with (currently only required for Twitter integration)
          required: false
          type: string
          default: |
            t35400dfzxcxvsdfn
            76gancHDHoad7a7fs
        - name: |
            twitter_digits
            [X-Auth-Service-Provider]
          in: formData
          description: Twitter Digits auth header to create User session with.
          required: false
          type: string
          default: |
            https://api.digits.com/1.1
            /sdk/account.json
        - name: |
            twitter_digits
            [X-Verify-Credentials-Authorization]
          in: formData
          description: Twitter Digits auth header to create User session with.
          required: false
          type: string
          default: |
            OAuth
            oauth_signature=...,
            oauth_nonce=...,
            oauth_timestamp=...,
            oauth_consumer_key=...,
            oauth_token=...,
            oauth_version=...,
            oauth_signature_method=...
        - name: firebase_phone[project_id]
          in: formData
          description: Firebase project ID - the unique identifier for your Firebase project.
          required: false
          type: string
          default: |
            my_app_project_id
        - name: firebase_phone[access_token]
          in: formData
          description: Firebase user's ID token.
          required: false
          type: string
          default: |
            t35400d....fzxcxvsdfn
      responses:
        '201':
          description: "Session object"
          schema:
            $ref: '#/definitions/SessionObject'
    get:
      summary:
        Retrieve session Info
      operationId: Retrieve_Session_Info_Id
      description:
        Get info about current session
      responses:
        '200':
          description: "Session object"
          schema:
            $ref: '#/definitions/SessionObject'
    delete:
      summary: Destroy session
      operationId: Destroy_Session_Id
      description: |
        Calling this method will remove and invalidate the session token
      responses:
        '200':
          description: Empty body
          schema:
            $ref: '#/definitions/EmptyBody'
definitions:
  EmptyBody:
    type: string
    default: 'null'
  SessionObject:
    type: object
    properties:
      _id:
        type: string
        example: 0e7bc95d85c0eb2bf052be3d29d3df523081e87f
      application_id:
        type: integer
        example: 92
      created_at:
        type: string
        example: "2012-04-03T07:34:48Z"
      nonce:
        type: integer
        example: 18945
      token:
        type: string
        example: "1e7bc99d85c0eb2bf062be3d29d3df523081e874"
      ts:
        type: integer
        example: 1473075233
      updated_at:
        type: string
        example: "2012-04-03T07:34:48Z"
      user_id:
        type: integer
        example: 302
      id:
        type: integer
        example: 326
