swagger: '2.0'
info:
  title: QuickBlox REST API, Users API.
  description: |
    The Users APIs manage all things related to user accounts handling, authentication, account data, password reminding etc:
      * OAuth is secure and supports transparent authentication;
      * Logging in users with their Facebook/Twitter/Twitter Digits accounts is available;
      * User tags – set up user tags and address them separately in your app or through the admin panel – supported by other modules such as Push Notifications;
      * Existing user base integration – our module supports connection to your system by storing your existent IDs table and matching them to new ones.
  version: 1.0
# the domain of the service
host: quickblox.com
# array of all schemes that QuickBlox API supports
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  /users.json:
    post:
      summary: Sign Up
      operationId: Users_1
      description: |
        Sign up a new user for the identification of the application users.
        QuickBlox enforces the uniqueness of the **login**, **email**, **facebook_id**, **twitter_id**, **twitter_digits_id** and **external_user_id** fields.
        You can ask QuickBlox to verify user email addresses (require email confirmation) in your application settings page in [Dashboard](https://admin.quickblox.com).
        Also you can setup custom email templates and pages for **Users greetings**, **Reset password** and **Email confirmation** features.
      parameters:
        - name: user[login]
          in: formData
          description: User login. At least **user[login]** or **user[email]** is required.
          required: true
          type: String
          default: samuelrulez
        - name: user[password]
          in: formData
          description: User password
          required: true
          type: string
          default: WzRAY9vrGmb6FfP
        - name: user[email]
          in: formData
          description: User email. At least **user[login]** or **user[email]** is required.
          required: true
          type: string
          default: awesomeemail@domain.com
        - name: user[full_name]
          in: formData
          description: User full name
          required: false
          type: string
          default: Captain Jack
        - name: user[phone]
          in: formData
          description: User phone number
          required: false
          type: string
          default: 4487556488
        - name: user[website]
          in: formData
          description: User web site
          required: false
          type: string
          default: https://quickblox.com
        - name: user[facebook_id]
          in: formData
          description: ID of the User in Facebook
          required: false
          type: string
          default: 100000883956766
        - name: user[twitter_id]
          in: formData
          description: ID of the User in Twitter
          required: false
          type: string
          default: 23434883956766
        - name: user[twitter_digits_id]
          in: formData
          description: ID of the User in Twitter digits
          required: false
          type: string
          default: 67434863956765
        - name: user[blob_id]
          in: formData
          description: 5346346
          required: false
          type: string
          default: ID of associated blob from Content module (for example, User avatar)
        - name: user[external_user_id]
          in: formData
          description: ID of User in external system
          required: false
          type: string
          default: 21445
        - name: user[tag_list]
          in: formData
          description: User tags – set up user tags and address them separately in your app.
          required: false
          type: string
          default: man,car,mac
        - name: user[custom_data]
          in: formData
          description: User's additional info
          required: false
          type: string
          default: age=34&lang=en
      responses:
        '201':
          description: "User object"
          schema:
            $ref: '#/definitions/UserResponse'
definitions:
  UserResponse:
    properties:
      user:
        $ref: '#/definitions/UserObject'
  UserObject:
    properties:
      id:
        type: integer
        example: 1639
      full_name:
        type: string
        example: John doe
      login:
        type: string
        example: samuelrulez
      phone:
        type: string
        example: 8765554351
      website:
        type: string
        example: https://quickblox.com
      created_at:
        type: string
        example: 2012-05-09T10:24:26Z
      updated_at:
        type: string
        example: 2012-05-09T10:24:26Z
      last_request_at:
        type: string
        example: 2012-05-09T10:24:26Z
      facebook_id:
        type: string
        example: 100000883956766
      twitter_id:
        type: string
        example: 23434883956766
      twitter_digits_id:
        type: string
        example: 67434863956765
      external_user_id:
        type: string
        example: 12334
      blob_id:
        type: string
        example: 234435
      custom_data:
        type: string
        example: age=34&lang=en
      user_tags:
        type: string
        example: man,car
