swagger: '2.0'
info:
  title: QuickBlox REST API, Content API.
  description: |
    Allows you to manage app contents and settings without having to re-publish them.
    Using a web interface you or your clients can control and make instant changes to the apps.<br>
    - To store chat file attachments<br>
    - Manage text, rich text, and media via easy to use web admin panel<br>
    - Can be used to manage ads and banners<br>
    - App synchronizes content in background, users not affected<br>
    - Any amount of data can be stored<br>
  version: 1.0
# the domain of the service
host: quickblox.com
# array of all schemes that QuickBlox API supports
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  /blobs.json:
    post:
      summary: Create file
      operationId: Create_File_Id
      description: |
        Create a new file.
      parameters:
        - name: blob[content_type]
          in: formData
          description: The file's mime [content type](https://developer.mozilla.org/ru/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types)
          required: true
          type: String
          default: image/jpeg
        - name: blob[name]
          in: formData
          description: The file's name
          required: true
          type: string
          default: museum.jpg
        - name: blob[public]
          in: formData
          description: The file's visibility. **public** means it will be possible to access this file without session token provided.
          required: true
          type: string
          default: false
      responses:
        '201':
          description: "File object"
          schema:
            $ref: '#/definitions/FileResponse'
definitions:
  FileResponse:
    properties:
      blob:
        $ref: '#/definitions/FileObject'
  FileObject:
    properties:
      id:
        type: integer
        example: 1639
      created_at:
        type: string
        example: 2012-05-09T10:24:26Z
      updated_at:
        type: string
        example: 2012-05-09T10:24:26Z
      name:
        type: string
        example: museum.jpg
      content_type:
        type: string
        example: image/jpeg
      public:
        type: boolean
        example: false
      size:
        type: integer
        example: 55332
      blob_status:
        type: string
        example: complete
      last_read_access_ts:
        type: string
        example: 2012-03-27T13:14:08Z
      set_completed_at:
        type: string
        example: 2012-03-23T16:14:51Z
      uid:
        type: string
        example: 859146a9821e4bef9c6d60e1e8c88b3c00
