swagger: '2.0'
info:
  title: QuickBlox REST API, Push Notifications API.
  description: |
    Employs QuickBlox servers’ power to send thousands of technical and marketing
    messages to your users. Two channels are supported:<br><br>
    • Push Notifications – sends iOS, Android, WP, BlackBerry pushes. This is being used for technical notifications, reminders and marketing messages. Also used as IM, enabling you or your users to send direct messages to other users (even if they are offline and not using the app). Can be integrated with other functions within the particular application.<br>
    • Emails – sending e-mails to your users. This is being used for users registration, password reminders, marketing newsletter etc<br>
    <br>
    Features:<br><br>
    • Messages Queue – messages can be either sent instantly or assigned a specific time/date and pushed into a Message Queue which allows to send delayed and recurring messages such as reminders, planned marketing announcements or any planned notifications for the better engagement of the users. <br>
    • Recurring notifications – set up a time interval and the message will be repeated automatically by the server. <br>
    • User tags - a feature powered by integration with our Users module, allowing to specify a group of users the message shall be sent to. <br>
    • Media attachments (send rich media attachments such as video, audio and location data, including video streaming, powered by our Content module). Not available for emails. <br>
    <br>
  version: 1.0
# the domain of the service
host: quickblox.com
# array of all schemes that QuickBlox API supports
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  /subscriptions.json:
    post:
      summary: Create subscription
      operationId: 101_Create_Subscription
      description: |
        Create device based subscription (subscribes).
      parameters:
        - name: notification_channel
          in: formData
          description: |
            Declare which notification channels could be used to notify user about events.
            Allowed values: **apns**, **apns_voip**, **gcm**, **mpns**, **bbps** and **email**.
          required: true
          type: string
          default: apns
        - name: push_token[environment]
          in: formData
          description: |
            Determine application mode. It allows conveniently separate development and production modes.
            Allowed values: **evelopment** or **production**.
          required: true
          type: enum
          default: development
        - name: push_token[bundle_identifier]
          in: formData
          description: |
            A unique identifier for client's application.
            In iOS, this is the Bundle Identifier. In Android - package id.
          required: false
          type: string
          default: com.quickblox.supresample
        - name: push_token[client_identification_sequence]
          in: formData
          description: |
            Identifies client device in 3-rd party service like APNS, GCM/FCM, BBPS or MPNS.
            Initially retrieved from 3-rd service and should be send to QuickBlox to let it send push notifications to the client.
          required: true
          type: string
          default: aa557232bc237245ba67686..
        - name: device[platform]
          in: formData
          description: |
            Platform of device, which is the source of application running.
            Allowed values: **ios**, **android**, **windows_phone**, **blackberry**.
          required: true
          type: string
          default: ios
        - name: device[udid]
          in: formData
          description: |
            UDID (Unique Device identifier) of device, which is the source of application running.
            This must be anything sequence which uniquely identify particular device.
            This is needed to support schema: 1 User - Multiple devices.
          required: true
          type: string
          default: 2343af3433aa3a4fsv
      responses:
        '201':
          description: "Array of all existent user's subscriptions"
          schema:
            $ref: '#/definitions/SubscriptionResponse'
    get:
      summary: Retrieve subscriptions
      operationId: 102_Retrieve_Subscriptions
      description: |
        Retrieve subscriptions for the user which is specified in the session token.
      responses:
        '200':
          description: "Array of all existent user's subscriptions"
          schema:
            $ref: '#/definitions/SubscriptionResponse'
  /subscriptions/{subscription_id}.json:
    delete:
      summary: Remove subscription
      operationId: 103_Remove_Subscription
      description: |
        Remove a subscription by its identifier (unsubscribes).
      parameters:
        - name: subscription_id
          in: formData
          description: An id of subscription to remove (path parameter)
          required: true
          type: integer
          default: 34891
      responses:
        '200':
          description: "Empty body"
definitions:
  SubscriptionResponse:
    properties:
      subscription:
        $ref: '#/definitions/SubscriptionObject'
  SubscriptionObject:
    properties:
      id:
        type: integer
        example: 1639
      notification_channel:
        $ref: '#/definitions/NotificationChannelObject'
      device:
        $ref: '#/definitions/DeviceObject'
  NotificationChannelObject:
    properties:
      name:
        type: string
        example: apns
  DeviceObject:
    properties:
      udid:
        type: string
        example: 3429C429-4C34-5214-8E3C-803AC0CA79ED
      platform:
        $ref: '#/definitions/PlatformObject'
  PlatformObject:
    properties:
      name:
        type: string
        example: ios
