swagger: '2.0'
info:
  title: QuickBlox REST API, Push Notifications API.
  description: |
    Employs QuickBlox servers’ power to send thousands of technical and marketing
    messages to your users. Two channels are supported:<br><br>
    • Push Notifications – sends iOS, Android, WP, BlackBerry pushes. This is being used for technical notifications, reminders and marketing messages. Also used as IM, enabling you or your users to send direct messages to other users (even if they are offline and not using the app). Can be integrated with other functions within the particular application.<br>
    • Emails – sending e-mails to your users. This is being used for users registration, password reminders, marketing newsletter etc<br>
    <br>
    Features:<br><br>
    • Messages Queue – messages can be either sent instantly or assigned a specific time/date and pushed into a Message Queue which allows to send delayed and recurring messages such as reminders, planned marketing announcements or any planned notifications for the better engagement of the users. <br>
    • Recurring notifications – set up a time interval and the message will be repeated automatically by the server. <br>
    • User tags - a feature powered by integration with our Users module, allowing to specify a group of users the message shall be sent to. <br>
    • Media attachments (send rich media attachments such as video, audio and location data, including video streaming, powered by our Content module). Not available for emails. <br>
    <br>
  version: 1.0
# the domain of the service
host: quickblox.com
# array of all schemes that QuickBlox API supports
schemes:
  - https
basePath: /api
produces:
  - application/json
paths:
  /blobs.json:
    post:
      summary: Create file
      operationId: Create_File_Id
      description: |
        Create a new file.
      parameters:
        - name: blob[content_type]
          in: formData
          description: The file's mime [content type](https://developer.mozilla.org/ru/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types)
          required: true
          type: String
          default: image/jpeg
        - name: blob[name]
          in: formData
          description: The file's name
          required: true
          type: string
          default: museum.jpg
        - name: blob[public]
          in: formData
          description: The file's visibility. **public** means it will be possible to access this file without session token provided.
          required: true
          type: string
          default: false
      responses:
        '201':
          description: "File object"
          schema:
            $ref: '#/definitions/FileResponse'
definitions:
  FileResponse:
    properties:
      blob:
        $ref: '#/definitions/FileObject'
  FileObjectAccess:
    properties:
      id:
        type: integer
        example: 4235
      blob_id:
        type: integer
        example: 163934
      object_access_type:
        type: string
        example: Write
      expires:
        type: string
        example: 2012-04-23T14:22:34Z
      params:
        type: string
        example: https://qbprod.s3.amazonaws.com/?Content-Type=image%2Fpng&Expires=Wed%2C%2030%20Sep%202015%2013%3A25%3A11%20GMT&acl=authenticated-read&key=fbc2d08125e3435ca5cb37f926d5fe8800&policy=eyJleHBpcmF0aW9uIjoiMjAxNS0wOS0zMFQxMzoyNToxMVoiLCJjb25kaXRpb25zIjpbeyJidWNrZXQiOiJxYnByb2QifSx7ImFjbCI6ImF1dGhlbnRpY2F0ZWQtcmVhZCJ9LHsiQ29udGVudC1UeXBlIjoiaW1hZ2UvcG5nIn0seyJzdWNjZXNzX2FjdGlvbl9zdGF0dXMiOiIyMDEifSx7IkV4cGlyZXMiOiJXZWQsIDMwIFNlcCAyMDE1IDEzOjI1OjExIEdNVCJ9LHsia2V5IjoiZmJjMmQwODEyNWUzNDM1Y2E1Y2IzN2Y5MjZkNWZlODgwMCJ9LHsieC1hbXotY3JlZGVudGlhbCI6IkFLSUFJWTdLRk0yM1hHWEo3UjdBLzIwMTUwOTMwL3VzLWVhc3QtMS9zMy9hd3M0X3JlcXVlc3QifSx7IngtYW16LWFsZ29yaXRobSI6IkFXUzQtSE1BQy1TSEEyNTYifSx7IngtYW16LWRhdGUiOiIyMDE1MDkzMFQxMjI1MTFaIn1dfQ%3D%3D&success_action_status=201&x-amz-algorithm=AWS4-HMAC-SHA256&x-amz-credential=AKIAIY7KFM23XGXJ7R7A%2F20150930%2Fus-east-1%2Fs3%2Faws4_request&x-amz-date=20150930T122511Z&x-amz-signature=a5c720c1a3b9b5c0b2549e0220419493ca3b11ce84618f6ece88ad97a96a8ad9
  FileObject:
    properties:
      id:
        type: integer
        example: 1639
      created_at:
        type: string
        example: 2012-05-09T10:24:26Z
      updated_at:
        type: string
        example: 2012-05-09T10:24:26Z
      name:
        type: string
        example: museum.jpg
      content_type:
        type: string
        example: image/jpeg
      public:
        type: boolean
        example: false
      size:
        type: integer
        example: 55332
      blob_status:
        type: string
        example: complete
      last_read_access_ts:
        type: string
        example: 2012-03-27T13:14:08Z
      set_completed_at:
        type: string
        example: 2012-03-23T16:14:51Z
      uid:
        type: string
        example: 859146a9821e4bef9c6d60e1e8c88b3c00
